Fix INDEX.LIST to prevent NoClassDefFoundError
  * Fixes NoClassDefFoundError per #30
  * Switch dist.zip to only contain applet
  * Adds README, LICENSE, CHANGELOG to applet